<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

$(document).ready(function(){
  $("#startButton").click(function(){
    not$("#startDiv").hide();
    ("#startDiv").show();
  });
  $("#raceButton").click(function(){
    not$("#raceDiv").hide();
    ("#raceDiv").show();
  });
  $("#classButton").click(function(){
    not$("#classDiv").hide();
    ("#classDiv").show();
  });
  $("#abButtons").click(function(){
    not$("#abDiv").hide();
    ("#abDiv").show();
  });
  $("#backgroundButton").click(function(){
    not$("#backgroundDiv").hide();
    ("#backgroundDiv").show();
  });
  $("#eqButton").click(function(){
    not$("#eqDiv").hide();
    ("#eqDiv").show();
  });
  $("#spButton").click(function(){
    not$("#spDiv").hide();
    ("#spDiv").show();
  });
  $("#featsButton").click(function(){
    not$("#featsDiv").hide();
    ("#featsDiv").show();
  });
  $("#bioButton").click(function(){
    not$("#bioDiv").hide();
    ("#bioDiv").show();
  });
  $("#reviewButton").click(function(){
    not$("#reviewDiv").hide();
    ("#reviewDiv").show();
  });
  $("#tabs").show();
});
